/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 desk2d.gltf --transform 
Files: desk2d.gltf [2.35KB] > /home/juan/Documents/new Database/newProject/JapanesseJoinery/my-joinery/public/desk2d-transformed.glb [437.55KB] (-18519%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimationFrame } from "framer-motion";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/desk2d-transformed.glb");
  const group = useRef();
  useAnimationFrame((state, delta) => {
    group.current.rotation.y += 0.00085 * delta;
    // console.log(state);
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Wood_Desk.geometry}
        material={materials["Material.002"]}
        position={[-0.051, -0.219, -0.01]}
        scale={1.3}
      />
    </group>
  );
}

useGLTF.preload("/desk2d-transformed.glb");
