/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 woodscene.gltf --transform 
Files: woodscene.gltf [76.5KB] > /home/juan/Documents/new Database/newProject/JapanesseJoinery/my-joinery/public/woodscene-transformed.glb [4.52MB] (-5811%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimationFrame } from "framer-motion";
export function WoodScene(props) {
  const { nodes, materials } = useGLTF("./woodscene-transformed.glb");
  const group = useRef();
  useAnimationFrame((state, delta) => {
    group.current.rotation.y += 0.00015 * delta;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      {/* <mesh
        geometry={nodes.Wood_chair.geometry}
        material={materials["brown wood"]}
        position={[2.273, 0.084, -2.852]}
      /> */}
      {/* <mesh
        geometry={nodes.Bolt_1.geometry}
        material={materials.PaletteMaterial001}
        position={[0.131, 0, -0.734]}
      />
      <mesh
        geometry={nodes.Part_1.geometry}
        material={materials.Wood}
        position={[0.131, 0, -0.734]}
      /> */}
      {/* <mesh
        geometry={nodes.assise002.geometry}
        material={materials["Material.002"]}
        position={[-1.089, 0.322, -1.735]}
        scale={[1.015, 1, 0.993]}
      /> */}
      <mesh
        geometry={nodes.banquette001.geometry}
        material={materials["Material.001"]}
        position={[-0.562, 0.203, -1.779]}
      />
      <mesh
        geometry={nodes.kitchen_table.geometry}
        material={materials.PaletteMaterial004}
        position={[-2.231, 0.71, -0.073]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.231, 0.655, -0.973]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.leg.geometry}
        material={materials.PaletteMaterial003}
        position={[-1.81, 0.327, -0.973]}
        rotation={[Math.PI / 2, -1.414, Math.PI / 2]}
      />
      {/* <mesh
        geometry={nodes.Levelers.geometry}
        material={materials.PaletteMaterial005}
        position={[0.955, 0.005, -3.947]}
        rotation={[0, Math.PI / 2, 0]}
      /> */}
      <mesh
        geometry={nodes.Table.geometry}
        material={materials["Teak wood polished"]}
        position={[1.629, 0, -3.947]}
        rotation={[0, 0.291, 0]}
      />
      <mesh
        geometry={nodes.side_table_01.geometry}
        material={materials.side_table_01}
        position={[0.995, 0, -1.899]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <instancedMesh
        args={[nodes.Bolt.geometry, materials.PaletteMaterial002, 11]}
        instanceMatrix={nodes.Bolt.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/woodscene-transformed.glb");
